/* prettier-ignore-start */

/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.27.5.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import * as functions from "../functions.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
const fullApi = {
  functions: functions,
};
export const api = fullApi;
export const internal = fullApi;

/* prettier-ignore-end */
